// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBDHb826qXXeDPSNBwJlyX7cmYA3J8QKc',
    appId: '1:993975469042:web:1a5ec54c4341bb13a8a16b',
    messagingSenderId: '993975469042',
    projectId: 'nihar14-ai-flutter-app',
    authDomain: 'nihar14-ai-flutter-app.firebaseapp.com',
    storageBucket: 'nihar14-ai-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbksh6kMNdBceR76RQdPYxFgHc5SE0p_A',
    appId: '1:993975469042:android:4d202f5384fb49c2a8a16b',
    messagingSenderId: '993975469042',
    projectId: 'nihar14-ai-flutter-app',
    storageBucket: 'nihar14-ai-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQhraROyD_m5yokWlnIvvq6cCUbh_Dx4',
    appId: '1:993975469042:ios:c64eeb018376af26a8a16b',
    messagingSenderId: '993975469042',
    projectId: 'nihar14-ai-flutter-app',
    storageBucket: 'nihar14-ai-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.aiHumanoidApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdQhraROyD_m5yokWlnIvvq6cCUbh_Dx4',
    appId: '1:993975469042:ios:c64eeb018376af26a8a16b',
    messagingSenderId: '993975469042',
    projectId: 'nihar14-ai-flutter-app',
    storageBucket: 'nihar14-ai-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.aiHumanoidApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBDHb826qXXeDPSNBwJlyX7cmYA3J8QKc',
    appId: '1:993975469042:web:34ad1c979c01ab98a8a16b',
    messagingSenderId: '993975469042',
    projectId: 'nihar14-ai-flutter-app',
    authDomain: 'nihar14-ai-flutter-app.firebaseapp.com',
    storageBucket: 'nihar14-ai-flutter-app.firebasestorage.app',
  );
}
